# Generated by Django 2.1.2 on 2018-11-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('target_price', models.FloatField(max_length=200)),
            ],
        ),
    ]
