# Generated by Django 2.1.2 on 2018-11-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0005_auto_20181109_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_stock_id',
        ),
        migrations.AddField(
            model_name='question',
            name='question_stock_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Stocks.StockDetail'),
            preserve_default=False,
        ),
    ]
