# Generated by Django 2.1.2 on 2018-11-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0007_auto_20181112_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='questionid',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='stockid',
            new_name='stock',
        ),
    ]
