# Generated by Django 2.1.2 on 2019-01-22 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0011_response_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
