# Generated by Django 2.1.2 on 2019-02-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0013_auto_20190125_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetail',
            name='company_logo',
            field=models.ImageField(default='default.jpg', upload_to='company_logos'),
        ),
    ]
