# Generated by Django 2.1.2 on 2019-03-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0015_auto_20190220_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='company_logo',
            field=models.ImageField(default='default.png', upload_to='company_logos/logos'),
        ),
    ]
