# Generated by Django 2.1.2 on 2019-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0017_auto_20190304_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response_text',
            field=models.CharField(max_length=201),
        ),
    ]
