# Generated by Django 2.1.2 on 2019-03-20 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stocks', '0018_auto_20190319_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetail',
            name='favourite',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
