# Generated by Django 2.1.2 on 2019-03-20 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0019_stockdetail_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
