# Generated by Django 2.1.2 on 2019-03-20 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0020_auto_20190320_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='favourite',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
