# Generated by Django 2.1.2 on 2019-04-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0023_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
