# Generated by Django 2.1.2 on 2019-04-08 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0024_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_function', models.CharField(max_length=201)),
                ('most_function', models.CharField(max_length=201)),
                ('improve_function', models.CharField(max_length=201)),
                ('rate_design', models.CharField(max_length=201)),
                ('most_design', models.CharField(max_length=201)),
                ('improve_design', models.CharField(max_length=201)),
                ('feedback_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
